version: 2.1

workflows:
  tests-deploy:
    jobs:
      -test



jobs:
  tests:
    docker:
      - image: cimg/node:20.2.0
    steps:
      - checkout
      - run: 
          name: install dependencies
          command: npm install
      - run: 
          name: Run Tests
          command: npx jest
      
